//=============================================================================
// MenuScreenOnboarding
// A very simple menu that simply described GMDX:AE features.
// Replaces the "show tips" button in the GMDX Options Menu
//=============================================================================

class MenuScreenGMDXOnboarding expands MenuScreenListWindowBig;

event InitWindow()
{
    //Mark onboarding as complete the moment we open the menu
    player.bDoneGMDXOnboarding = true;
    player.SaveConfig();
	Super.InitWindow();
}

defaultproperties
{
     items(0)=(HelpText="The GMDX Help menu contains information regarding new features, changes and additions made by GMDX. This menu contains many tips and tricks and should be read thoroughly for a comprehensive understanding of how to play GMDX: Augmented Edition.|n|nMost of the features listed in this menu are optional and can be enabled or disabled using the Quality of Life and Gameplay menus.|n|nNOTE: This menu can be opened again using the 'Show Help Menu' button in the GMDX Options Screen",actionText="About the Help Menu",image1="OBM_HelpMenu2",image2="OBM_HelpMenu1",sortcategory="00TOP0")
     items(1)=(HelpText="A headshot with a tranquilizer dart is an instant non-lethal takedown to any unarmoured human NPC.|n|nNOTE: Range Mods will increase crossbow arc trajectory and improve your chances of getting headshots.",actionText="Crossbow Headshots",image1="OBM_CrossHeadshot1",image2="OBM_CrossHeadshot2")
     items(2)=(HelpText="Items can be assigned as Secondaries.|n|nSecondary items are quick-use items that can be used instantly with a single keypress. Using a secondary item is quicker than selecting an item from the toolbelt.|n|nTo assign an item as a secondary, use the 'Assign Secondary' button or press the 'Use Secondary Item' key (Default: F) in the Inventory screen.|n|nNOTE: Your accuracy bonus from standing still is not reset when using most secondary items.",actionText="Assigning Secondary Items",image1="OBM_Secondaries1",image2="OBM_Secondaries2")
     items(3)=(HelpText="Variations of mouse clicking on items in the inventory acts as shortcuts. Right click to equip or use, middle mouse to drop. Press Spacebar to rotate items.|n|nNOTE: Holding Shift while dropping items will drop an entire stack.",actionText="Extended Inventory Controls",image1="OBM_Inventory1",image2="OBM_Inventory2")
     items(4)=(HelpText="Double press interact (Default: Right Mouse Button) or use the Left Mouse button to pick up a corpse regardless of inventory limitations.|n|nNOTE: Carcasses will never be picked up the first time they are interacted with, even if they are empty.",actionText="Enhanced Carcass Interactions",image1="OBM_Carcass1",image2="OBM_Carcass2")
     items(5)=(HelpText="You can interact with many objects by Left-Clicking while your hands are empty.|n|n - Inventory Items: You will put them in your hands or use them where they stand.|n - Doors, Crates and Interactables: You will pull out a lockpick, multitool, a melee weapon or the Nanokey, depending on context.|n - Carcasses: You will pick them up, regardless of inventory state.|n|nNOTE: Some objects have unique interactions. Try experimenting with left-click interactions for other object types!",actionText="Left-Click Interactions",image1="OBM_LeftInteract1",image2="OBM_LeftInteract2")
     items(6)=(HelpText="Open the Augmentation Wheel (Default: C) to see and use all of your available augmentations at a glance.|n|nAugmentations can be added or removed from the Augmentation Wheel using the Middle Mouse button while in the Augmentations screen.|n|nThe Augmentation Wheel has extensive configuration options, available in the Quality of Life menu.|n|nNOTE: By default, only Active augmentations are added to the wheel.",actionText="Augmentation Wheel",image1="OBM_AugWheel1",image2="OBM_AugWheel2")
     items(7)=(HelpText="Augmentations come in 4 distinct types:|n|n - Passive (Yellow): Always active, and drain no energy.|n - Active (Blue): Manually activated, use energy when in use.|n - Automatic (Light Blue): Manually Activated, will drain energy under certain conditions, such as when reducing radiation damage or when lifting heavy objects.|n - Toggle (Green): Manually activated, will immediately drain an energy reserve when activated, which lowers your maximum bioelectrical energy capacity, but drain no energy while active.|n|nNOTE: Your currently reserved energy is shown as red on the Bioenergy Bar in the HUD and Augmentation Screen.",actionText="Augmentation Types",image1="OBM_Augment1",image2="OBM_Augment2")
     items(8)=(HelpText="The Keyring has its own special slot on the toolbelt.|n|nThis slot can also be used for normal items, by dragging them onto the keyring.|nIf an item is removed from the slot, the keyring will become available once again.|n|nNOTE: The keyring can always be used via left-click interactions, the assigned keyboard key (Default: '), or by right-clicking the NanoKey icon in the inventory screen.",actionText="Using the Keyring Slot",image1="OBM_Keyring1",image2="OBM_Keyring2")
     items(9)=(HelpText="With the Heavily Tweaked perk (Heavy Weapons: ADVANCED), you can attach scopes and lasers to the GEP Gun.|n|nWhen using the scope or the laser, missiles can be guided, allowing attacking targets around corners or over obstacles.|n|nNOTE: Flight time is dependent on range. By adding Range mods, you can improve flight time. Default flight time is about 5 seconds.",actionText="GEP Rocket Guidance",image1="OBM_GepGun1",image2="OBM_GepGun2")
     items(10)=(HelpText="JC will use stamina while running, swimming, and mantling.|n|nStamina is not recovered while crouching.|n|nAvailable stamina and mantle height are determined by your Athletics skill.|n|nNOTE: Being poisoned will severely restrict stamina recovery. Try to remain in cover when under the effects of tranquiliser darts or tear gas.",actionText="Mantling and Stamina Use",image1="OBM_Stamina1",image2="OBM_Stamina2")
     items(11)=(HelpText="Scopes, Silencers and Laser Sights are bulky and will add penalties when attached to any weapon.|n|nThese attachments can be added or removed using the inventory screen or the relevant hotkey, and should be attached or detached as needed for any given combat situation.|n|nThe Wetwork perk negates addon penalties entirely.|n|nNOTE: Once attached to a weapon, attachments can be added and removed freely but won't return to your inventory and cannot be used on any other weapon.",actionText="Attachment Bulk",image1="OBM_Attachment1",image2="OBM_Attachment2")
     items(12)=(HelpText="Unwanted items can be declined by using the 'Decline' and 'Decline (Global)' buttons in the Inventory screen.|n|nDeclined items will not automatically be picked up from carcasses or when interacting with them in the world. Holding your run/walk key will override your preferences and allow picking up declined items. Items can be removed from the decline list at any time in the Inventory screen.|n|nNOTE: Items that are declined globally will also be declined in future playthroughs.",actionText="Declining Items",image1="OBM_Decline1",image2="OBM_Decline2")
     items(13)=(HelpText="Explosives can be rearmed and reused, based on your Demolitions skill.|n|nAfter disarming an explosive, it will appear as 'Disarmed' in the HUD. Interact with it to add it to your inventory. If you lack the Demolitions skill to rearm it, or if you disable it using EMP, it will instead show as 'Disabled' and cannot be rearmed.|n|nNOTE: Grenades can always be disarmed by interacting with them. Demolitions skill only affects their ability to rearmed and reused.",actionText="Rearming Grenades",image1="OBM_Grenade1",image2="OBM_Grenade2")
     items(14)=(HelpText="The Dragon's Tooth Sword has an internal power supply which will drain energy when attacking.|n|nIt can be recharged using biocells, and will benefit from the 'Field Repair' perk.|n|nThe Dragon's Tooth is an extremely potent and powerful weapon, but should be used sparingly in order to minimise energy drain and biocell use.|n|nNOTE: The Dragon's Tooth Sword is most effective when honed using Damage mods.",actionText="Dragons Tooth Energy Use",image1="OBM_DragonTooth1",image2="OBM_DragonTooth2")
     items(15)=(HelpText="JC can only eat a certain amount of food before becoming full.|n|nOnce full, JC will not be able to eat any more food items for a time.|n|nCandy Bars will give bioenergy as well as health and are a good source of emergency power, and Soy Food is more effective than Soda, so try to eat healthy when possible!|n|nNOTE: Hunger decrease is based on progression, not time, so you cannot simply wait in one location for it to decrease.",actionText="Hunger",image1="OBM_Hunger1",image2="OBM_Hunger2")
     items(16)=(HelpText="Using Cigarettes, Alcohol and Zyme will give specific, positive effects, such as increased health or accuracy for a few minutes at a time, while also increasing addiction level.|n|nIf consumed too much within a short time, JC will become addicted. Once addicted, JC must continue to consume these substances or suffer withdrawal penalties. Dependence will reduce and withdrawals will heal automatically based on game progression, not time.|n|nNOTE: This feature is only available when using the 'Addiction System' playthrough modifier, otherwise these items will behave as normal.",image1="OBM_Addiction1",image2="OBM_Addiction2",actionText="Addictions and Withdrawals")
     items(17)=(HelpText="Tranquiliser Darts will break upon hitting a hard surface, such as a wall or door.|n|nCrossbow ammo should be managed carefully to avoid running out.|n|nNOTE: By default only Tranquiliser darts are effected. This can be changed in the Gameplay menu to extend to all dart types.",actionText="Crossbow Dart Recovery",image1="OBM_CrossDart1",image2="OBM_CrossDart2")
     items(18)=(HelpText="It's very important to remain quiet and move slowly while in stealth. Attacking enemies using melee weapons while undetected from behind will give a significant damage bonus, up to 12x, dependent on your Stealth skill.|n|nThe Stealth skill plays a major part in your ability to remain undetected, controlling your visibility as well as your footstep volume while running, walking and crouching.|n|nMake sure to not leave corpses in view of cameras, as they will set off the alarm if they spot a carcass.|n|nNOTE: Unconscious enemies do not trigger camera alarms.",actionText="Stealth and Detection",image1="OBM_Stealth1",image2="OBM_Stealth2")
     items(19)=(HelpText="Each skill comes with its own set of perks.|n|nPerks give unique benefits, such as faster scope times, long range multitool use, silent ladder use, and extra explosion radius. Perks can be purchased for skill points at any time by clicking the 'Perks' button in the Skills menu.|n|nPerks come with skill level requirements, and start at Trained in a given skill. General perks can be purchased at any time and do not require skill investment, but cost a large number of skill points.|n|nNOTE: General Perks can be accessed by double-pressing the Perks button in the Skills screen.",actionText="Perks",image1="OBM_Perk1",image2="OBM_Perk2")
     items(20)=(HelpText="When hacking security systems, disabled cameras and turrets will reboot and become active again after a certain time period, dependent on Computers skill.|n|nContinually hacking the same console will eventually result in network detection, permanently disabling it.|n|nTo disable security devices permanently, consider using a multitool rather than hacking, or finding the password.|n|nNOTE: Terminal lockouts only apply to security computers, personal terminals are unaffected and can be hacked infinitely.",actionText="Security Reboots and Lockouts",image1="OBM_Reboot1",image2="OBM_Reboot2")
     items(21)=(HelpText="Playthrough Modifiers are large-scale changes that effect an entire playthrough, such as adding item randomization or restricting saving. Playthrough Modifiers must be activated before starting a new game, and cannot be changed during a playthrough.|n|nPlaythrough Modifiers can be accessed using the 'Modifiers' button in the new-game screen.|n|nNOTE: Some modifiers (such as Restricted Saving) are always enabled in Hardcore mode and won't appear in the Modifiers menu.",actionText="Playthrough Modifiers",image1="OBM_PlayModifier1",image2="OBM_PlayModifier2")
     items(22)=(HelpText="MJ12 Elites and some other enemies are equipped with thermoptic camo. They will become invisible during combat and won't appear on your HUD or be identified on the crosshair.|n|nNOTE: The Vision Enhancement augmentation can be used to see cloaked enemies. Tech Goggles can also be used if you have the Thermal Imaging perk.",actionText="Cloaked Enemies",image1="OBM_Cloaking1",image2="OBM_Cloaking2")
     items(23)=(HelpText="Equipment items rely on internal batteries, which can be recharged using Repair Bots and Bioelectric Cells. Total effectiveness and battery drain is dependent on the Environmental Training skill.|n|nSome items, such as Ballistic Vests and Hazmat Suits, only drain upon taking damage, while others drain constantly while equipped.|n|nSome items will remain equipped when drained, but will be ineffective. Recharge them to continue benefitting from their effects. The Field Repair perk can improve the effectiveness of equipment recharges.|n|nNOTE: On Higher difficulties, repair bots will have limited recharges, and some items like Rebreathers will become disposable and non-rechargable. Manage your energy carefully!",actionText="Equipment Items",image1="OBM_EqItem1",image2="OBM_EqItem2")
     items(24)=(HelpText="Hardcore Mode enforces all of the Gameplay options available in the Gameplay menu.|n|nHardcore mode additionally adds a number of other gameplay mechanics, such as limited saving, limited Repair Bot and Medical Bot charges, harder lockpicking/bypassing, and more.|n|nNOTE: Hardcore mode is extremely difficult and is not recommended for first time players of GMDX.",actionText="Hardcore Mode",image1="OBM_Hardcore1",image2="OBM_Hardcore2")
     items(25)=(HelpText="Doors for which you have the key can be locked using the Nanokey. Doors locked by the player can not be opened by NPCs, allowing blocking off flanking routes and other points of access for enemies.|n|nNOTE: The Locksport perk will allow locking anything you have previously picked, allowing you to lock a significant number of doors.",actionText="Locking Doors",image1="OBM_LockDoors1",image2="OBM_LockDoors2")
     items(26)=(HelpText="Markers can be placed using the Add Marker button in the Goals/Notes screen.|n|nMarkers will appear in the world and allow you to tag critical locations or items.|n|nNOTE: Marker visibility can be toggled using the Show Markers checkbox in the Goals/Notes screen.",actionText="Markers",image1="OBM_Marker1",image2="OBM_Marker2")
     items(27)=(HelpText="Notes can be pinned using the Pin Note button in the Goals/Notes Screen.|n|nPinned Notes will always appear at the top of the notes list.|n|nThis behaviour can be changed in the Quality of Life menu.|n|nNOTE: Goals can also be displayed on the HUD using the 'Display Goals on Screen' checkbox.",actionText="Pinned Notes",image1="OBM_PinNote1",image2="OBM_PinNote2")
     items(28)=(HelpText="Repair Bots can be used to recharge equipment items, while Medical Bots can provide Healing, Augmentation installation and Trauma Recovery services.|n|nMedical and Repair bots have limited charges, based on difficulty. Once out of charges, they cannot be reused.|n|nNOTE: The number of medical and repair bots is significantly reduced in Hardcore mode.",actionText="Repair and Medical Bots",image1="OBM_RepairMedBot1",image2="OBM_RepairMedBot2")
     items(29)=(HelpText="Tech Goggles and the Vision Enhancement Augmentation can be used to see cameras and turrets through walls.|n|nItems will also be highlighted at short range, including the contents of crates and other breakables.|n|nNOTE: This is very useful for seeing items in lockboxes and other locked containers or behind locked doors.",actionText="Thermal Imaging",image1="OBM_ThermImg1",image2="OBM_ThermImg2")
     items(30)=(HelpText="If enabled, Traumas will accumulate as you take damage, depending on damage type.|n|nTraumas add negative effects, such as lower health or less effective medkit use. Traumas can be healed using medkits or by using a Medical bot.|n|nNOTE: Curing Traumas will consume a charge on Medical Bots, which may limit their usefulness on higher difficulties.",actionText="Traumas",image1="OBM_Trauma1",image2="OBM_Trauma2")
     items(31)=(HelpText="Inventory items, such as weapons and ammo, can be picked up and carried in your hands by holding your Walk/Run key while interacting with them.|n|nThis allows stockpiling ammo for later, or moving items when out of inventory space.|n|nNOTE: This can be used to carry Datacubes and other readable items too.",actionText="Carrying Items",image1="OBM_Carryables1",image2="OBM_Carryables2")
     items(32)=(HelpText="Items which cannot be interacted with or are declined will be highlighted with a red border.|n|nSome items which can be interacted with but not picked up or which have have restricted usefulness will be highlighted with a blue border. For example:|n - Books/Datacubes which have previously been read.|n - Carcasses which have been searched|n - Food items which can be eaten with left-click but which cannot fit into your inventory|n - Weapons which can be looted for ammo but which cannot fit into your inventory|n|nNOTE: Some items like Augmentation Canisters will have a blue border for other reasons, such as if one of the augmentations in the canister can be replaced.",actionText="Highlight Colors (Items)",image1="OBM_FrobColors1",image2="OBM_FrobColors2")
     items(33)=(HelpText="Augmentation Canisters each contain a pair of augmentations. If additional Canisters are found, Augmentations can be replaced with their opposite, as long as there are no slots free on the relevant body part.|n|nNOTE: Augmentations will be installed at level 1, but can still be upgraded by Synthetic Heart",actionText="Augmentation Replacement",image1="OBM_AugRepl1",image2="OBM_AugRepl2")
     items(34)=(HelpText="Synthetic Heart will passively upgrade all Augmentations by 1 level.|n|nAny augmentations that are already at max level will instead 'spill over' their upgrade to a different augmentation.|n|nThe order in which augmentations are upgraded is preset based on body positions and is not affected by installation order or any other factors.|n|nNOTE: You can see which augmentations have been upgraded by looking at the augmentation levels at a Medical Bot.",actionText="Synthetic Heart Upgrades",image1="OBM_SynthHeart1",image2="OBM_SynthHeart2")
     items(35)=(HelpText="The Change Ammo Key (default: X) will swap selected grenades, melee weapons, and other items, similar to Shifter.|n|nThis can be used for all disposable weapons (grenades, PS20, Throwing Knives, etc) as well as wearables.|n|nItems that are already present on the belt will be skipped when quick-swapping to a new item.|n|nNOTE: This feature can be extensively customized. See the 'Change Ammo Swaps Items' item in the Quality of Life menu.",actionText="Item Quick-Swapping",image1="Qol_AmmoSwapItem1",image2="Qol_AmmoSwapItem2")
     items(36)=(HelpText="The Game's Launcher contains many important options. Renderer, resolution, FOV and more can be adjusted here.|n|nFor best results, either use the DirectX 9 renderer in Fullscreen mode, or the DirectX 10 renderer in Borderless Windowed mode. Streamers should use DirectX 10 while streaming, while regular players are encouraged to use DirectX 9.|n|nIf you experience audio crackling, try increasing or decreasing audio latency.|n|nNOTE: The mod comes bundled with DXVK, which can be enabled by running the 'dxvk_enable.cmd' file in the Deus Ex System folder.",actionText="The GMDX Launcher",image1="OBM_GMDXLaunch1",image2="OBM_GMDXLaunch2",sortCategory="00TOP1")
     items(37)=(HelpText="The GMDX Settings menus allow configuring the mod to your needs. The Quality of Life menu provides options for managing preferences and non-gameplay related settings, while the Gameplay menu allows changing gameplay settings. All gameplay menu settings are always enabled when playing in Hardcore mode. The HDTP Menu allows toggling HDTP models on and off in real-time for every object in the game.|n|nIn each menu, the search box (available with Ctrl-F) can allow you to find and tweak individual settings quickly and easily.|n|nNOTE: The Advanced Menu, available within the Quality of Life menu, allows significant configuration of GMDX:AE and is recommended for advanced users only.",actionText="GMDX Settings Menus",image1="OBM_GMDXMenu1",image2="OBM_GMDXMenu2",sortCategory="00TOP2")
     items(38)=(HelpText="Keypads, Doors and Containers for which you have the relevant key or code will be highlighted in green. When Left-Clicking, the Nano Keyring will be selected instead of a Lockpick.|n|nNOTE: This feature is disabled in Hardcore mode.",actionText="Highlight Colors (Locked Objects)",image1="OBM_FrobColKey1",image2="OBM_FrobColKey2")
     items(39)=(HelpText="By holding both the Lean-Left and Lean-Right keys at the same time, you can peek over boxes and other small objects.|n|nNOTE: Peeking is quicker than crouching, but doesn't give you as much height as standing up.",actionText="Tiptoes",image1="OBM_Tiptoes1",image2="OBM_Tiptoes2")
     

     Title="GMDX Help and Features"
     consoleTarget=""
     bShowDefaults=false
     actionButtons(0)=(Align=HALIGN_Right,Action=AB_OK) //The cancel button becomes the OK button
     actionButtons(1)=(Action=AB_None) //SARGE: Remove the OK button
     actionButtons(2)=(Action=AB_None) //SARGE: Remove the Reset button
     bShowValueInHelp=false
     bLeftEdgeActive=false
}
