//=============================================================================
// MenuScreenOnboarding
// A very simple menu that simply described GMDX:AE features.
// Replaces the "show tips" button in the GMDX Options Menu
//=============================================================================

class MenuScreenGMDXOnboarding expands MenuScreenListWindowBig;

event InitWindow()
{
    //Mark onboarding as complete the moment we open the menu
    player.bDoneGMDXOnboarding = true;
    player.SaveConfig();
	Super.InitWindow();
}

defaultproperties
{
     items(0)=(HelpText="The GMDX Help menu contains information regarding new features, changes and additions made by GMDX. This menu contains many tips and tricks and should be read thoroughly for a comprehensive understanding of how to play GMDX: Augmented Edition.|n|nMost of the features listed in this menu are optional and can be enabled or disabled using the Quality of Life and Gameplay menus.|n|nNOTE: This menu can be opened when needed using the 'Show Help Menu' button in the GMDX Options Screen",actionText="About the Help Menu",image1="OBM_HelpMenu1",sortcategory="00TOP0")
     items(1)=(HelpText="A headshot with a tranquilizer dart is an instant non-lethal takedown to any unarmoured human NPC.|n|nNOTE: Range Mods can increase crossbow arc trajectory and improve your chances of getting headshots.",actionText="Crossbow Headshots",image1="OBM_CrossHeadshot1",image2="OBM_CrossHeadshot2")
     items(2)=(HelpText="Items can be assigned as Secondaries.|n|nSecondary items are quick-use items that can be used instantly with a single keypress.|n|nTo assign an item as a secondary, use the 'Assign Secondary' button or press the use secondary key (Default: F) in the Inventory screen.|n|nNOTE: Your accuracy bonus from standing still is not reset when using most secondary items.",actionText="Assigning Secondary Items",image1="OBM_Secondaries1",image2="OBM_Secondaries2")
     items(3)=(HelpText="Variations of mouse clicking on items in the inventory acts as shortcuts. Right click to equip or use, middle mouse to drop. Press Spacebar to rotate items.|n|nNOTE: Holding Shift while dropping items will drop an entire stack.",actionText="Extended Inventory Controls",image1="OBM_Inventory1",image2="OBM_Inventory2")
     items(4)=(HelpText="Double press interact (Default: Right Mouse Button) or use the Left Mouse button to pick up a corpse regardless of inventory limitations.",actionText="Enhanced Carcass Interactions",image1="OBM_Carcass1",image2="OBM_Carcass2")
     items(5)=(HelpText="You can interact with many objects by Left-Clicking while your hands are empty.|n|n - Inventory Items: You will put them in your hands or use them where they stand.|n - Doors, Crates and Interactables: You will pull out a lockpick, multitool, a melee weapon or the Nanokey, depending on context.|n - Carcasses: You will pick them up, regardless of inventory state.|n|nNOTE: Some objects have unique interactions. Try experimenting with left-click interactions for other object types!",actionText="Left-Click Interactions",image1="OBM_LeftInteract1",image2="OBM_LeftInteract2")
     items(6)=(HelpText="Open the Augmentation Wheel (Default: C) to see and use all of your available augmentations at a glance.|n|nAugmentations can be added or removed from the Augmentation Wheel using the Middle Mouse button while in the Augmentations screen.|n|nThe Augmentation Wheel has extensive configuration options, available in the settings menu.|n|nNote: By default, only Active augmentations are added to the wheel.",actionText="Augmentation Wheel",image1="OBM_AugWheel1",image2="OBM_AugWheel2")
     items(7)=(HelpText="Augmentations come in 4 distinct types:|n|n - Passive (Yellow): Always active, and drain no energy.|n - Active (Blue): Manually activated, use energy when in use.|n - Automatic (Light Blue): Manually Activated, will drain energy under certain conditions, such as when reducing radiation damage or when lifting heavy objects.|n - Toggle (Green): Manually activated, will immediately drain an energy reserve when activated, which lowers your maximum bioelectrical energy capacity, but drain no energy while active.",actionText="Augmentation Types",image1="OBM_Augment1",image2="OBM_Augment2")
     items(8)=(HelpText="The Keyring has it's own special slot on the toolbelt.|n|nThis slot can also be used for normal items, by dragging them onto the keyring.|nIf an item is removed from the slot, the keyring will become available once again.|n|nNOTE: The keyring can always be used via left-click interactions, the assigned keyboard key (Default: '), or by right-clicking the NanoKey icon in the inventory screen.",actionText="Using the Keyring Slot",image1="OBM_Keyring1",image2="OBM_Keyring2")
     items(9)=(HelpText="With the Heavily Tweaked perk (Heavy Weapons: ADVANCED), you can attach scopes and lasers to the GEP Gun.|n|nWhen using the scope or the laser, missiles can be guided, allowing attacking targets around corners or over obstacles.|n|nNOTE: Flight time is dependent on range. By adding more Range mods, you can improve flight time. Default flight time is about 5 seconds.",actionText="GEP Rocket Guidance",image1="OBM_GepGun1",image2="OBM_GepGun2")
     items(10)=(HelpText="JC will use stamina while running, swimming, and mantling.|n|nAvailable stamina and mantle height are determined by your Athletics skill.|n|nNOTE: Being poisoned will severely restrict stamina recovery. Try to remain in cover when under the effects of tranquiliser darts or tear gas.",actionText="Mantling and Stamina Use.",image1="OBM_Stamina1",image2="OBM_Stamina2")
     items(11)=(HelpText="Scopes, Silencers and Laser Sights are bulky and will add penalties when attached to any weapon.|n|nThese attachments can be added or removed using the inventory screen or the relevant hotkey, and should be attached or detached as needed for any given combat situation.|n|nThe Wetwork perk negates addon penalties entirely.|n|nNOTE: Once attached to a weapon, attachments can be added and removed freely but won't return to your inventory and cannot be used on any other weapon.",actionText="Attachment Bulk",image1="OBM_Attachment1",image2="OBM_Attachment2")
     items(12)=(HelpText="Unwanted items can be declined by using the 'Decline' and 'Decline (Global)' buttons in the Inventory screen.|n|nDeclined items will not automatically be picked up from carcasses or when right-clicking items in the world. Holding your run/walk key will override your preferences and allow picking up declined items. Items can be removed from the decline list at any time in the Inventory screen.|n|nNOTE: Items that are declined globally will also be declined in future playthroughs.",actionText="Declining Items",image1="OBM_Decline1",image2="OBM_Decline2")
     items(13)=(HelpText="Explosives can be rearmed and reused, based on your Demolitions skill.|nAfter disarming an explosive, it will appear as 'Disarmed' in the HUD. Right-Click to add it to your inventory.|nIf you lack the Demolitions skill to rearm it, or if you disables it using EMP, it will instead show as 'Disabled' and cannot be rearmed.|n|nNOTE: Grenades can always be disarmed by right-clicking on them. Demolition skill only affects their ability to rearmed and reused.",actionText="Rearming Grenades",image1="OBM_Grenade1",image2="OBM_Grenade2")
     items(14)=(HelpText="The Dragon's Tooth Sword has an internal power supply which will drain energy when attacking.|n|nIt can be recharged using biocells, and will benefit from the 'Field Repair' perk.|n|nThe Dragon's Tooth is an extremely potent and powerful weapon, but should be used sparingly in order to minimise energy drain and biocell use.|n|nNOTE: The Dragon's Tooth Sword is most effective when honed using Damage mods.",actionText="Dragons Tooth Energy Use",image1="OBM_DragonTooth1",image2="OBM_DragonTooth2")
     items(15)=(HelpText="JC can only eat a certain amount of food before becoming full.|n|nOnce full, JC will not be able to eat any more food items for a time.|n|nCandy Bars will give bioenergy as well as health and are a good source of emergency power, and Soy Food is more effective than Soda, so try to eat healthy when possible!|n|nNOTE: Hunger decrease is based on progression, not time, so you cannot simply wait in one location to eat again.",actionText="Hunger",image1="OBM_Hunger1",image2="OBM_Hunger2")
     items(16)=(HelpText="Using Cigarettes, Alcohol and Zyme will give specific, positive effects, such as increased health or accuracy for a few minutes at a time, while also increasing addiction level.|n|nIf consumed too much within a short time, JC will become addicted. Once addicted, JC must continue to consume these substances or suffer withdrawal penalties.|n|nDependence will reduce and withdrawals will heal automatically over time.|n|nThis feature is only available when using the 'Addiction System' playthrough modifier, otherwise these items will behave as normal.|n|nNOTE: Addiction decrease is based on progression, not time, so you cannot simply wait in one location to cure withdrawal effects.",image1="OBM_Addiction1",image2="OBM_Addiction2",actionText="Addictions and Withdrawals")
     items(17)=(HelpText="Tranquiliser Darts will break upon hitting a hard surface, such as a wall or door.|n|nCrossbow ammo should be managed carefully to avoid running out.|n|nNOTE: By default only Tranquiliser darts are effected. This can be changed in the Gameplay settings to extend to all dart types.",actionText="Crossbow Dart Recovery",image1="OBM_CrossDart1",image2="OBM_CrossDart2")
     items(18)=(HelpText="It's very important to remain quiet and move slowly while in stealth. Attacking enemies using melee weapons while undetected from behind will give a significant damage bonus, up to 12x, dependant on your Stealth skill.|n|nThe Stealth skill plays a major part in your ability to remain undetected, controlling your visibility as well as your footstep volume while running, walking and crouching.|n|nMake sure to not leave corpses in view of cameras, as they will set off the alarm if they spot a carcass.|n|nNOTE: Unconscious enemies do not trigger camera alarms.",actionText="Stealth and Detection",image1="OBM_Stealth1",image2="OBM_Stealth2")
     items(19)=(HelpText="Each skill comes with it's own set of perks.|n|nPerks give unique benefits, such as faster scope times, long range multitool use, silent ladder use, and extra explosion radius.|n|nPerks can be purchased for skill points at any time by clicking the 'Perks' button in the Skills menu.|n|nPerks come with skill level requirements, and start at Trained in a given skill. General perks can be purchased at any time and do not require skill investment, but cost a large number of skill points.|n|nNOTE: General Perks can be accessed by double-pressing the Perks button in the Skills screen.",actionText="Perks",image1="OBM_Perk1",image2="OBM_Perk2")
     items(20)=(HelpText="When hacking security systems, disabled cameras and turrets will reboot and become active again after a certain time period, dependent on Computers skill.|n|nContinually hacking the same console will eventually result in network detection, permanently disabling the terminal.|n|nTo disable security devices permanently, consider using a multitool rather than hacking, or finding the password.|n|nNOTE: Terminal lockouts only apply to security computers, personal terminals are unaffected and can be hacked infinitely.",actionText="Security Reboots and Lockouts",image1="OBM_Reboot1",image2="OBM_Reboot2")
     items(21)=(HelpText="Playthrough Modifiers are large-scale changes that effect an entire playthrough, such as adding item randomization or restricting saving. Playthrough Modifiers must be activated before starting a new game, and cannot be changed during a playthrough.|n|nPlaythrough Modifiers can be accessed using the 'Modifiers' button in the new-game screen.",actionText="Playthrough Modifiers",image1="OBM_PlayModifier1",image2="OBM_PlayModifier2")
     

     Title="GMDX Help and Features"
     consoleTarget=""
     bShowDefaults=false
     actionButtons(0)=(Align=HALIGN_Right,Action=AB_OK) //The cancel button becomes the OK button
     actionButtons(1)=(Action=AB_None) //SARGE: Remove the OK button
     actionButtons(2)=(Action=AB_None) //SARGE: Remove the Reset button
     bShowValueInHelp=false
     bLeftEdgeActive=false
}
