//=============================================================================
// MenuScreenHDTPToggles                                                        //RSD: Adapted from MenuScreenCustomizeKeys.uc so I can steal the scrolling window
//=============================================================================

class MenuScreenHDTPToggles expands MenuScreenListWindow;

//Update Models
function SaveSettings()
{
    Super.SaveSettings();
    player.HDTP();
}

event bool ListRowActivated(window list, int rowId)
{
    Super.ListRowActivated(list,rowId);
    player.HDTP();
}

// ----------------------------------------------------------------------
// ----------------------------------------------------------------------

defaultproperties
{
     //items(9)=(actionText="MJ12 Trooper",consoleTarget="DeusExPlayer",variable="bHDTP_MJ12");
     strHeaderActionLabel="Object"
     strHeaderAssignedLabel="Model"
     HelpText="Select the model you wish to change and then press [Enter] or Double-Click to cycle through available models"
     Items(0)=(actionText="JC Denton",variable="bHDTP_JC",consoleTarget="DeusExPlayer")
     Items(1)=(actionText="Paul Denton",variable="bHDTP_Paul",consoleTarget="DeusExPlayer")
     Items(2)=(actionText="Gunther Hermann",variable="bHDTP_Gunther",consoleTarget="DeusExPlayer")
     Items(3)=(actionText="Anna Navarre",variable="bHDTP_Anna",consoleTarget="DeusExPlayer")
     Items(4)=(actionText="Nicolette DuClare",variable="bHDTP_Nico",consoleTarget="DeusExPlayer")
     Items(5)=(actionText="NSF Terrorist",variable="bHDTP_NSF",consoleTarget="DeusExPlayer")
     Items(6)=(actionText="Riot Cop",variable="bHDTP_RiotCop",consoleTarget="DeusExPlayer")
     Items(7)=(actionText="Walton Simons",variable="bHDTP_Walton",consoleTarget="DeusExPlayer")
     Items(8)=(actionText="UNATCO Trooper",variable="bHDTP_Unatco",consoleTarget="DeusExPlayer")
     Items(9)=(actionText="Cleaner Bot",defaultValue=1,consoleTarget="DeusEx.CleanerBot")
     Items(10)=(actionText="Military Bot",defaultValue=1,consoleTarget="DeusEx.MilitaryBot")
     Items(11)=(actionText="Medical Bot",defaultValue=1,consoleTarget="DeusEx.MedicalBot")
     Items(12)=(actionText="Repair Bot",defaultValue=1,consoleTarget="DeusEx.RepairBot")
     Items(13)=(actionText="Security Bot (Large)",defaultValue=1,consoleTarget="DeusEx.SecurityBot2")
     Items(14)=(actionText="Security Bot (Small)",defaultValue=1,consoleTarget="DeusEx.SecurityBot3")
     Items(15)=(actionText="Spider Bot 1",defaultValue=1,consoleTarget="DeusEx.SpiderBot")
     Items(16)=(actionText="Spider Bot (Mini)",defaultValue=1,consoleTarget="DeusEx.SpiderBot2")
     Items(17)=(actionText="Spider Bot (Mini #2)",defaultValue=1,consoleTarget="DeusEx.SpiderBot3")
     Items(18)=(actionText="Spider Bot (Mini #3)",defaultValue=1,consoleTarget="DeusEx.SpiderBot4")
     Items(19)=(actionText="Gray",defaultValue=1,consoleTarget="DeusEx.Gray")
     Items(20)=(actionText="Greasel",defaultValue=1,consoleTarget="DeusEx.Greasel")
     Items(21)=(actionText="Karkian",defaultValue=1,consoleTarget="DeusEx.Karkian")
     Items(22)=(actionText="Auto Turret",defaultValue=1,consoleTarget="DeusEx.AutoTurret")
     Items(23)=(actionText="Assault Gun",defaultValue=1,consoleTarget="DeusEx.WeaponAssaultGun")
     Items(24)=(actionText="Assault Shotgun",defaultValue=1,consoleTarget="DeusEx.WeaponAssaultShotgun")
     Items(25)=(actionText="Baton",consoleTarget="DeusEx.WeaponBaton")
     Items(26)=(actionText="Combat Knife",defaultValue=1,consoleTarget="DeusEx.WeaponCombatKnife")
     Items(27)=(actionText="Crowbar",defaultValue=1,consoleTarget="DeusEx.WeaponCrowbar")
     Items(28)=(actionText="EMP Grenade",consoleTarget="DeusEx.WeaponEMPGrenade")
     Items(29)=(actionText="Flamethrower",defaultValue=1,consoleTarget="DeusEx.WeaponFlamethrower")
     Items(30)=(actionText="Gas Grenade",consoleTarget="DeusEx.WeaponGasGrenade")
     Items(31)=(actionText="GEP Gun",defaultValue=1,consoleTarget="DeusEx.WeaponGEPGun")
     Items(32)=(actionText="LAM",consoleTarget="DeusEx.WeaponLAM")
     Items(33)=(actionText="LAW",defaultValue=1,consoleTarget="DeusEx.WeaponLAW")
     Items(34)=(actionText="Mini-Crossbow",defaultValue=1,consoleTarget="DeusEx.WeaponMiniCrossbow")
     Items(35)=(actionText="Dragons Tooth Sword",defaultValue=1,consoleTarget="DeusEx.WeaponNanoSword")
     Items(36)=(actionText="Scramble Grenade",consoleTarget="DeusEx.WeaponNanoVirusGrenade")
     Items(37)=(actionText="Pepper Spray",defaultValue=1,consoleTarget="DeusEx.WeaponPepperGun")
     Items(38)=(actionText="Pistol",defaultValue=1,consoleTarget="DeusEx.WeaponPistol")
     Items(39)=(actionText="Plasma Rifle",defaultValue=1,consoleTarget="DeusEx.WeaponPlasmaRifle")
     Items(40)=(actionText="Riot Prod",consoleTarget="DeusEx.WeaponProd")
     Items(41)=(actionText="Sniper Rifle",valueText2="FOMOD Beta",defaultValue=1,consoleTarget="DeusEx.WeaponRifle")
     Items(42)=(actionText="Sawed-Off Shotgun",valueText2="FOMOD Beta",defaultValue=2,consoleTarget="DeusEx.WeaponSawedOffShotgun")
     Items(43)=(actionText="Stealth Pistol",valueText2="FOMOD Beta",defaultValue=1,consoleTarget="DeusEx.WeaponStealthPistol")
     Items(44)=(actionText="Sword",defaultValue=1,consoleTarget="DeusEx.WeaponSword")
     Items(45)=(actionText="Throwing Knives",defaultValue=1,consoleTarget="DeusEx.WeaponShuriken")
     Items(46)=(actionText="AI Prototype",defaultValue=1,consoleTarget="DeusEx.AIPrototype")
     Items(47)=(actionText="Alarm Unit",defaultValue=1,consoleTarget="DeusEx.AlarmUnit")
     Items(48)=(actionText="Alarm Light",defaultValue=1,consoleTarget="DeusEx.AlarmLight")
     Items(49)=(actionText="Ambrosia Container",defaultValue=1,consoleTarget="DeusEx.BarrelAmbrosia")
     Items(50)=(actionText="Augmentation Cannister",defaultValue=1,consoleTarget="DeusEx.AugmentationCannister")
     Items(51)=(actionText="Augmentation Upgrade",defaultValue=1,consoleTarget="DeusEx.AugmentationUpgradeCannister")
     Items(52)=(actionText="Augmentation Override",defaultValue=1,consoleTarget="DeusEx.AugmentationUpgradeCannisterOverdrive")
     Items(53)=(actionText="Barrel",defaultValue=1,consoleTarget="DeusEx.Barrel1")
     Items(54)=(actionText="Barrel (Flaming)",defaultValue=1,consoleTarget="DeusEx.BarrelFire")
     Items(55)=(actionText="Basket",defaultValue=1,consoleTarget="DeusEx.Basket")
     Items(56)=(actionText="Basketball",defaultValue=1,consoleTarget="DeusEx.Basketball")
     Items(57)=(actionText="Bench 1",defaultValue=1,consoleTarget="DeusEx.WHBenchEast")
     Items(58)=(actionText="Bench 2",defaultValue=1,consoleTarget="DeusEx.WHBenchLibrary")
     Items(59)=(actionText="Bone (Femur)",defaultValue=1,consoleTarget="DeusEx.BoneFemur")
     Items(60)=(actionText="Bone (Femur 2)",defaultValue=1,consoleTarget="DeusEx.BoneFemurBloody")
     Items(61)=(actionText="Binoculars",defaultValue=1,consoleTarget="DeusEx.Binoculars")
     Items(62)=(actionText="Book (Open)",defaultValue=1,consoleTarget="DeusEx.BookOpen")
     Items(63)=(actionText="Book (Closed)",valueText2="HDTP (Extended Covers)",defaultValue=2,consoleTarget="DeusEx.BookClosed")
     Items(64)=(actionText="Book (Newspaper)",defaultValue=1,consoleTarget="DeusEx.Newspaper")
     Items(65)=(actionText="Button",defaultValue=1,consoleTarget="DeusEx.Button1")
     Items(66)=(actionText="Candy Bar",defaultValue=1,consoleTarget="DeusEx.Candybar")
     Items(67)=(actionText="Cage Light",defaultValue=1,consoleTarget="DeusEx.CageLight")
     Items(68)=(actionText="Cardboard Box (Large)",defaultValue=1,consoleTarget="DeusEx.BoxLarge")
     Items(69)=(actionText="Cardboard Box (Medium)",defaultValue=1,consoleTarget="DeusEx.BoxMedium")
     Items(70)=(actionText="Cardboard Box (Small)",defaultValue=1,consoleTarget="DeusEx.BoxSmall")
     Items(71)=(actionText="Cat",defaultValue=1,consoleTarget="DeusEx.Cat")
     Items(72)=(actionText="Chair",defaultValue=1,consoleTarget="DeusEx.Chair1")
     Items(73)=(actionText="Chair (Leather)",defaultValue=1,consoleTarget="DeusEx.ChairLeather")
     Items(74)=(actionText="Chair (Swivel Chair)",defaultValue=1,consoleTarget="DeusEx.OfficeChair")
     Items(75)=(actionText="Chair (Dining Chair)",defaultValue=1,consoleTarget="DeusEx.WHChairDining")
     Items(76)=(actionText="Chair (Fancy)",defaultValue=1,consoleTarget="DeusEx.WHChairOvalOffice")
     Items(77)=(actionText="Cigarettes",defaultValue=1,consoleTarget="DeusEx.Cigarettes")
     Items(78)=(actionText="Cigarette Machine",defaultValue=1,consoleTarget="DeusEx.CigaretteMachine")
     Items(79)=(actionText="Computer (Personal)",defaultValue=1,consoleTarget="DeusEx.ComputerPersonal")
     Items(80)=(actionText="Computer (Security)",defaultValue=1,consoleTarget="DeusEx.ComputerSecurity")
     Items(81)=(actionText="Computer (ATM)",defaultValue=1,consoleTarget="DeusEx.ATM")
     Items(82)=(actionText="Concrete Barricade",defaultValue=1,consoleTarget="DeusEx.RoadBlock")
     Items(83)=(actionText="Control Panel",defaultValue=1,consoleTarget="DeusEx.ControlPanel")
     Items(84)=(actionText="Couch (Leather)",defaultValue=1,consoleTarget="DeusEx.LeatherCouch")
     Items(85)=(actionText="Couch (Red)",defaultValue=1,consoleTarget="DeusEx.WHRedCouch")
     Items(86)=(actionText="Credit Chit",defaultValue=1,consoleTarget="DeusEx.Credits")
     Items(87)=(actionText="Cushion",defaultValue=1,consoleTarget="DeusEx.Cushion")
     Items(88)=(actionText="Data Cube",defaultValue=1,consoleTarget="DeusEx.DataCube")
     Items(89)=(actionText="Earth",defaultValue=1,consoleTarget="DeusEx.Earth")
     Items(90)=(actionText="Fan 1",defaultValue=1,consoleTarget="DeusEx.Fan1")
     Items(91)=(actionText="Fan 2",defaultValue=1,consoleTarget="DeusEx.Fan2")
     Items(92)=(actionText="Fan 3",defaultValue=1,consoleTarget="DeusEx.Fan1Vertical")
     Items(93)=(actionText="Fan (Ceiling Fan)",defaultValue=1,consoleTarget="DeusEx.CeilingFan")
     Items(94)=(actionText="Fan (Ceiling Fan Motor)",defaultValue=1,consoleTarget="DeusEx.CeilingFanMotor")
     Items(95)=(actionText="Faucet",defaultValue=1,consoleTarget="DeusEx.Faucet")
     Items(96)=(actionText="Fire Plug",defaultValue=1,consoleTarget="DeusEx.FirePlug")
     Items(97)=(actionText="Flag Pole",defaultValue=1,consoleTarget="DeusEx.FlagPole")
     Items(98)=(actionText="Flare",defaultValue=1,consoleTarget="DeusEx.Flare")
     Items(99)=(actionText="Flower Pot",defaultValue=1,consoleTarget="DeusEx.Flowers")
     Items(100)=(actionText="Keypad 1",defaultValue=1,consoleTarget="DeusEx.Keypad1")
     Items(101)=(actionText="Keypad 2",defaultValue=1,consoleTarget="DeusEx.Keypad2")
     Items(102)=(actionText="Keypad 3",defaultValue=1,consoleTarget="DeusEx.Keypad3")
     Items(103)=(actionText="Lab Flask",defaultValue=1,consoleTarget="DeusEx.Flask")
     Items(104)=(actionText="Lamp 1",defaultValue=1,consoleTarget="DeusEx.Lamp1")
     Items(105)=(actionText="Lamp 2",defaultValue=1,consoleTarget="DeusEx.Lamp2")
     Items(106)=(actionText="Lamp 3",defaultValue=1,consoleTarget="DeusEx.Lamp3")
     Items(107)=(actionText="Light Bulb",defaultValue=1,consoleTarget="DeusEx.LightBulb")
     Items(108)=(actionText="Light Switch",defaultValue=1,consoleTarget="DeusEx.LightSwitch")
     Items(109)=(actionText="Liquor",defaultValue=1,consoleTarget="DeusEx.LiquorBottle")
     Items(110)=(actionText="Liquor (Forty)",defaultValue=1,consoleTarget="DeusEx.Liquor40oz")
     Items(111)=(actionText="Liquor (Wine)",defaultValue=1,consoleTarget="DeusEx.WineBottle")
     Items(112)=(actionText="Mailbox",defaultValue=1,consoleTarget="DeusEx.Mailbox")
     Items(113)=(actionText="Medical Kit",defaultValue=1,consoleTarget="DeusEx.MedKit")
     Items(114)=(actionText="Microscope",defaultValue=1,consoleTarget="DeusEx.Microscope")
     Items(115)=(actionText="Nanovirus Container",defaultValue=1,consoleTarget="DeusEx.BarrelVirus")
     Items(116)=(actionText="Pan 1",defaultValue=1,consoleTarget="DeusEx.Pan1")
     Items(117)=(actionText="Pan 2",defaultValue=1,consoleTarget="DeusEx.Pan2")
     Items(118)=(actionText="Pan 3",defaultValue=1,consoleTarget="DeusEx.Pan3")
     Items(119)=(actionText="Pan 4",defaultValue=1,consoleTarget="DeusEx.Pan4")
     Items(120)=(actionText="Pillow",defaultValue=1,consoleTarget="DeusEx.Pillow")
     Items(121)=(actionText="Pinball Machine",defaultValue=1,consoleTarget="DeusEx.Pinball")
     Items(122)=(actionText="Plant 1",defaultValue=1,consoleTarget="DeusEx.Plant1")
     Items(123)=(actionText="Plant 2",defaultValue=1,consoleTarget="DeusEx.Plant2")
     Items(124)=(actionText="Plant 3",defaultValue=1,consoleTarget="DeusEx.Plant3")
     Items(125)=(actionText="Police Boat",defaultValue=1,consoleTarget="DeusEx.NYPoliceBoat")
     Items(126)=(actionText="Pool Ball",defaultValue=1,consoleTarget="DeusEx.PoolBall")
     Items(127)=(actionText="Pot 1",defaultValue=1,consoleTarget="DeusEx.Pot1")
     Items(128)=(actionText="Pot 2",defaultValue=1,consoleTarget="DeusEx.Pot2")
     Items(129)=(actionText="Rat",defaultValue=1,consoleTarget="DeusEx.Rat")
     Items(130)=(actionText="Retinal Scanner",defaultValue=1,consoleTarget="DeusEx.RetinalScanner")
     Items(131)=(actionText="Satellite Dish",defaultValue=1,consoleTarget="DeusEx.SatelliteDish")
     Items(132)=(actionText="Ships Wheel",defaultValue=1,consoleTarget="DeusEx.ShipsWheel")
     Items(133)=(actionText="Shop Light",defaultValue=1,consoleTarget="DeusEx.Shoplight")
     Items(134)=(actionText="Shop Light (Hanging)",defaultValue=1,consoleTarget="DeusEx.HangingShopLight")
     Items(135)=(actionText="Shower Faucet",defaultValue=1,consoleTarget="DeusEx.ShowerFaucet")
     Items(136)=(actionText="Shower Head",defaultValue=1,consoleTarget="DeusEx.ShowerHead")
     Items(137)=(actionText="Soda Can",defaultValue=1,consoleTarget="DeusEx.SodaCan")
     Items(138)=(actionText="Soy Food",defaultValue=1,consoleTarget="DeusEx.SoyFood")
     Items(139)=(actionText="Subway Control Panel",defaultValue=1,consoleTarget="DeusEx.SubwayControlPanel")
     Items(140)=(actionText="Supply Crate (General)",defaultValue=1,consoleTarget="DeusEx.CrateBreakableMedGeneral")
     Items(141)=(actionText="Supply Crate (Combat)",defaultValue=1,consoleTarget="DeusEx.CrateBreakableMedCombat")
     Items(142)=(actionText="Supply Crate (Medical)",defaultValue=1,consoleTarget="DeusEx.CrateBreakableMedMedical")
     Items(143)=(actionText="Switch",defaultValue=1,consoleTarget="DeusEx.Switch1")
     Items(144)=(actionText="TNT Crate",defaultValue=1,consoleTarget="DeusEx.CrateExplosiveSmall")
     Items(145)=(actionText="Telephone",defaultValue=1,consoleTarget="DeusEx.Phone")
     Items(146)=(actionText="Telephone Answering Machine",defaultValue=1,consoleTarget="DeusEx.TAD")
     Items(147)=(actionText="Toilet",defaultValue=1,consoleTarget="DeusEx.Toilet")
     Items(148)=(actionText="Toilet (Urinal)",defaultValue=1,consoleTarget="DeusEx.Toilet2")
     Items(149)=(actionText="Trashcan 1",defaultValue=1,consoleTarget="DeusEx.TrashCan1")
     Items(150)=(actionText="Trashcan 2",defaultValue=1,consoleTarget="DeusEx.TrashCan2")
     Items(151)=(actionText="Trashcan 3",defaultValue=1,consoleTarget="DeusEx.TrashCan3")
     Items(152)=(actionText="Trashcan 4",defaultValue=1,consoleTarget="DeusEx.TrashCan4")
     Items(153)=(actionText="Trashbag 1",defaultValue=1,consoleTarget="DeusEx.Trashbag")
     Items(154)=(actionText="Trashbag 2",defaultValue=1,consoleTarget="DeusEx.Trashbag2")
     Items(155)=(actionText="Trash (Paper)",defaultValue=1,consoleTarget="DeusEx.TrashPaper")
     Items(156)=(actionText="Tree 1",defaultValue=1,consoleTarget="DeusEx.Tree1")
     Items(157)=(actionText="Tree 2",defaultValue=1,consoleTarget="DeusEx.Tree2")
     Items(158)=(actionText="Tree 3",defaultValue=1,consoleTarget="DeusEx.Tree3")
     Items(159)=(actionText="Tree 4",defaultValue=1,consoleTarget="DeusEx.Tree4")
     Items(160)=(actionText="Trophy",defaultValue=1,consoleTarget="DeusEx.Trophy")
     Items(161)=(actionText="Tumbleweed",defaultValue=1,consoleTarget="DeusEx.Tumbleweed")
     Items(162)=(actionText="Unbreakable Crate (Large)",defaultValue=1,consoleTarget="DeusEx.CrateUnbreakableLarge")
     Items(163)=(actionText="Unbreakable Crate (Medium)",defaultValue=1,consoleTarget="DeusEx.CrateUnbreakableMed")
     Items(164)=(actionText="Unbreakable Crate (Small)",defaultValue=1,consoleTarget="DeusEx.CrateUnbreakableSmall")
     Items(165)=(actionText="Utility Push-Cart",defaultValue=1,consoleTarget="DeusEx.Cart")
     Items(166)=(actionText="Valve",defaultValue=1,consoleTarget="DeusEx.Valve")
     Items(167)=(actionText="Vase 1",defaultValue=1,consoleTarget="DeusEx.Vase1")
     Items(168)=(actionText="Vase 2",defaultValue=1,consoleTarget="DeusEx.Vase2")
     Items(169)=(actionText="Vending Machine",defaultValue=1,consoleTarget="DeusEx.VendingMachine")
     Items(170)=(actionText="Water Cooler",defaultValue=1,consoleTarget="DeusEx.WaterCooler")
     Items(171)=(actionText="Water Fountain",defaultValue=1,consoleTarget="DeusEx.WaterFountain")
     Items(172)=(actionText="Wet Floot Sign",defaultValue=1,consoleTarget="DeusEx.FloorSign")
     Items(173)=(actionText="10mm Ammo",defaultValue=1,consoleTarget="DeusEx.Ammo10mm")
     Items(174)=(actionText="10mm AP Ammo",defaultValue=1,consoleTarget="DeusEx.Ammo10mmAP")
     Items(175)=(actionText="20mm Ammo",defaultValue=1,consoleTarget="DeusEx.Ammo20mm")
     Items(176)=(actionText="20mm EMP Ammo",defaultValue=1,consoleTarget="DeusEx.Ammo20mmEMP")
     Items(177)=(actionText="762mm Ammo",defaultValue=1,consoleTarget="DeusEx.Ammo762mm")
     Items(178)=(actionText="3006 Ammo",defaultValue=1,consoleTarget="DeusEx.Ammo3006")
     Items(179)=(actionText="Darts",defaultValue=1,consoleTarget="DeusEx.AmmoDart")
     Items(180)=(actionText="Darts (Flare)",defaultValue=1,consoleTarget="DeusEx.AmmoDartFlare")
     Items(181)=(actionText="Darts (Poison)",defaultValue=1,consoleTarget="DeusEx.AmmoDartPoison")
     Items(182)=(actionText="Darts (Taser)",defaultValue=1,consoleTarget="DeusEx.AmmoDartTaser")
     Items(183)=(actionText="Napalm",defaultValue=1,consoleTarget="DeusEx.AmmoNapalm")
     Items(184)=(actionText="Plasma Ammo",defaultValue=1,consoleTarget="DeusEx.AmmoPlasma")
     Items(185)=(actionText="Prod Charger",defaultValue=1,consoleTarget="DeusEx.AmmoBattery")
     Items(186)=(actionText="Rockets",defaultValue=1,consoleTarget="DeusEx.AmmoRocket")
     Items(187)=(actionText="WP Rockets",defaultValue=1,consoleTarget="DeusEx.AmmoRocketWP")
     Items(188)=(actionText="Shells",defaultValue=1,consoleTarget="DeusEx.AmmoShell")
     Items(189)=(actionText="Shells (Sabot)",defaultValue=1,consoleTarget="DeusEx.AmmoSabot")
     Items(190)=(actionText="Shells (Rubber)",defaultValue=1,consoleTarget="DeusEx.AmmoRubber")
     Items(191)=(actionText="Blood and Decals",defaultValue=1,consoleTarget="DeusEx.DeusExDecal")
     Title="HDTP Model Options"
     disabledText="Vanilla"
     enabledText="HDTP"
     variable="iHDTPModelToggle"
}
