# SARGE: Show FPS
# dxvk.hud = fps

# SARGE: Required, don't change this!
dxvk.allowFse = True

# SARGE: Required, don't change this
dxgi.maxFrameRate = 119
d3d9.maxFrameRate = 119

# SARGE: Disable v-sync
d3d9.presentInterval = 0
dxgi.syncInterval = 0

# SARGE: Minimise latency
dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1